server:
  port: 8888
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:example
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update